// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ColorModesController from "./color_modes_controller"
application.register("color-modes", ColorModesController)

import FormController from "./form_controller"
application.register("form", FormController)

import QuillEditorController from "./quill_editor_controller"
application.register("quill-editor", QuillEditorController)

import QuillViewerController from "./quill_viewer_controller"
application.register("quill-viewer", QuillViewerController)

import ScrollPreserverController from "./scroll_preserver_controller"
application.register("scroll-preserver", ScrollPreserverController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)

import ToastsController from "./toasts_controller"
application.register("toasts", ToastsController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
