---
require:
- rubocop-performance
- rubocop-rails
- rubocop-capybara
- rubocop-factory_bot
- rubocop-rspec
Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true
Style/ClassAndModuleChildren:
  SafeAutoCorrect: true
