# frozen_string_literal: true

# Technology list
class Technology
  class << self
    def collection
      LIST
    end
  end

  LIST = %w[
    .net
    .net-3.5
    .net-4.0
    .net-core
    2d
    3d
    64-bit
    accessibility
    actionscript
    actionscript-3
    active-directory
    activemq
    activerecord
    adb
    admob
    ado.net
    adobe
    aes
    aggregate
    aggregate-functions
    aggregation-framework
    air
    airflow
    ajax
    akka
    alamofire
    algorithm
    alignment
    amazon-cloudformation
    amazon-cognito
    amazon-dynamodb
    amazon-ec2
    amazon-elastic-beanstalk
    amazon-rds
    amazon-redshift
    amazon-s3
    amazon-web-services
    anaconda
    android
    android-actionbar
    android-activity
    android-alertdialog
    android-animation
    android-asynctask
    android-camera
    android-edittext
    android-emulator
    android-fragments
    android-gradle-plugin
    android-intent
    android-layout
    android-listview
    android-manifest
    android-ndk
    android-recyclerview
    android-room
    android-service
    android-sqlite
    android-studio
    android-viewpager
    android-volley
    android-webview
    android-widget
    angular
    angular-cli
    angular-material
    angular-ui-router
    angular5
    angular6
    angular7
    angularjs
    angularjs-directive
    angularjs-ng-repeat
    angularjs-scope
    animation
    annotations
    ansible
    ant
    apache
    apache-camel
    apache-flex
    apache-flink
    apache-kafka
    apache-pig
    apache-poi
    apache-spark
    apache-spark-sql
    apache2
    api
    apk
    app-store
    app-store-connect
    append
    appium
    apple-push-notifications
    applescript
    applet
    apply
    architecture
    arduino
    arguments
    arm
    arraylist
    arrays
    artificial-intelligence
    ascii
    asp-classic
    asp.net
    asp.net-ajax
    asp.net-core
    asp.net-core-mvc
    asp.net-core-webapi
    asp.net-identity
    asp.net-mvc
    asp.net-mvc-2
    asp.net-mvc-3
    asp.net-mvc-4
    asp.net-mvc-5
    asp.net-web-api
    asp.net-web-api2
    assembly
    associations
    async-await
    asynchronous
    attributes
    audio
    authentication
    authorization
    autocomplete
    autolayout
    automapper
    automated-tests
    automation
    average
    avfoundation
    awk
    aws-api-gateway
    aws-lambda
    aws-sdk
    awt
    axios
    azure
    azure-active-directory
    azure-blob-storage
    azure-cosmosdb
    azure-devops
    azure-functions
    azure-pipelines
    azure-sql-database
    azure-storage
    azure-web-app-service
    babeljs
    backbone.js
    backend
    background
    background-image
    backup
    bar-chart
    base64
    bash
    batch-file
    beautifulsoup
    big-o
    bigdata
    binary
    binary-search-tree
    binary-tree
    binding
    bit-manipulation
    bitbucket
    bitmap
    blackberry
    blazor
    blob
    blockchain
    bluetooth
    bluetooth-lowenergy
    boolean
    boost
    bootstrap-4
    bootstrap-modal
    border
    botframework
    boto3
    bots
    branch
    broadcastreceiver
    browser
    buffer
    build
    build.gradle
    bundle
    button
    byte
    c
    c-preprocessor
    c#
    c#-4.0
    c++
    c++-cli
    c++11
    c++14
    c++17
    caching
    cakephp
    calendar
    callback
    camera
    canvas
    capybara
    carousel
    case
    cassandra
    casting
    celery
    centos
    certificate
    cgi
    char
    character
    character-encoding
    chart.js
    charts
    chat
    checkbox
    chef-infra
    ckeditor
    clang
    class
    classification
    click
    client
    client-server
    clojure
    closures
    cloud
    cluster-analysis
    cluster-computing
    cmake
    cmd
    cocoa
    cocoa-touch
    cocoapods
    cocos2d-iphone
    codeigniter
    codeigniter-3
    coding-style
    coffeescript
    coldfusion
    collections
    colors
    com
    combinations
    combobox
    command
    command-line
    command-line-interface
    comments
    common-lisp
    compare
    comparison
    compilation
    compiler-construction
    compiler-errors
    components
    composer-php
    compression
    computer-vision
    concatenation
    concurrency
    conda
    conditional
    conditional-statements
    config
    configuration
    connection
    console
    console-application
    constants
    constraints
    constructor
    containers
    content-management-system
    continuous-integration
    controller
    controls
    conv-neural-network
    cookies
    coordinates
    copy
    cordova
    cordova-plugins
    core-data
    cors
    couchdb
    count
    crash
    create-react-app
    cron
    cross-browser
    cross-domain
    cross-platform
    cryptography
    crystal-reports
    css
    css-animations
    css-float
    css-position
    css-selectors
    css-transitions
    csv
    cucumber
    cuda
    curl
    cursor
    cxf
    cygwin
    cypher
    cypress
    d3.js
    dart
    data-binding
    data-science
    data-structures
    data-visualization
    data.table
    database
    database-connection
    database-design
    dataframe
    datagrid
    datagridview
    dataset
    datatable
    datatables
    date
    datepicker
    datetime
    dax
    db2
    debian
    debugging
    decimal
    deep-learning
    delegates
    delphi
    dependencies
    dependency-injection
    deployment
    deserialization
    design-patterns
    devexpress
    devise
    devops
    dialog
    dialogflow-es
    dictionary
    directory
    directx
    discord
    discord.js
    discord.py
    django
    django-admin
    django-forms
    django-models
    django-queryset
    django-rest-framework
    django-templates
    django-views
    dll
    dns
    docker
    docker-compose
    dockerfile
    doctrine
    doctrine-orm
    docusignapi
    dojo
    dom
    dom-events
    domain-driven-design
    double
    download
    dplyr
    drag-and-drop
    drawing
    driver
    drop-down-menu
    dropdown
    drupal
    drupal-7
    duplicates
    dynamic
    dynamic-programming
    dynamics-crm
    e-commerce
    echo
    eclipse
    eclipse-plugin
    eclipse-rcp
    ecmascript-6
    editor
    ef-code-first
    ejb
    ejs
    elasticsearch
    electron
    elixir
    eloquent
    emacs
    email
    embedded
    ember-data
    ember.js
    encoding
    encryption
    entity
    entity-framework
    entity-framework-4
    entity-framework-6
    entity-framework-core
    enums
    environment-variables
    erlang
    error-handling
    escaping
    eslint
    ethereum
    etl
    event-handling
    events
    excel
    excel-2010
    excel-formula
    exception
    exception-handling
    exe
    exec
    expo
    export
    express
    expression
    extjs
    extjs4
    extract
    f#
    facebook
    facebook-graph-api
    facebook-javascript-sdk
    fancybox
    fetch
    ffmpeg
    fft
    field
    file
    file-io
    file-upload
    filesystems
    filter
    filtering
    find
    firebase
    firebase-authentication
    firebase-cloud-messaging
    firebase-realtime-database
    firebase-storage
    firefox
    firefox-addon
    flash
    flask
    flask-sqlalchemy
    flexbox
    floating-point
    fluent-nhibernate
    flutter
    flutter-layout
    focus
    font-awesome
    fonts
    for-loop
    foreach
    foreign-keys
    fork
    format
    formatting
    forms
    formula
    fortran
    fragment
    frameworks
    frontend
    ftp
    full-text-search
    fullcalendar
    function
    functional-programming
    g++
    garbage-collection
    gatsby
    gcc
    gdb
    gem
    generator
    generics
    geolocation
    geometry
    get
    ggplot2
    gis
    git
    github
    gitlab
    gitlab-ci
    glassfish
    global-variables
    glsl
    gmail
    gnuplot
    go
    google-analytics
    google-api
    google-app-engine
    google-apps-script
    google-bigquery
    google-calendar-api
    google-chrome
    google-chrome-devtools
    google-chrome-extension
    google-cloud-datastore
    google-cloud-firestore
    google-cloud-functions
    google-cloud-messaging
    google-cloud-platform
    google-cloud-storage
    google-colaboratory
    google-compute-engine
    google-drive-api
    google-kubernetes-engine
    google-maps
    google-maps-api-3
    google-maps-markers
    google-oauth
    google-play
    google-play-services
    google-sheets
    google-sheets-formula
    google-visualization
    gps
    gpu
    gradle
    grails
    graph
    graphics
    graphql
    grep
    grid
    gridview
    groovy
    group-by
    grouping
    grpc
    gruntjs
    gson
    gtk
    gulp
    gwt
    gzip
    hadoop
    handlebars.js
    hash
    hashmap
    hashtable
    haskell
    hbase
    hdfs
    header
    heap-memory
    height
    heroku
    hex
    hibernate
    highcharts
    histogram
    hive
    homebrew
    hook
    hosting
    hover
    html
    html-lists
    html-parsing
    html-table
    html5-canvas
    html5-video
    http
    http-headers
    http-post
    http-status-code-404
    httpclient
    httprequest
    https
    httpwebrequest
    hyperledger-fabric
    hyperlink
    ibm-cloud
    ibm-mobilefirst
    icons
    ide
    identityserver4
    if-statement
    iframe
    iis
    iis-7
    image
    image-processing
    imagemagick
    imageview
    import
    in-app-purchase
    include
    indexing
    inheritance
    initialization
    inner-join
    input
    insert
    instagram
    installation
    instance
    int
    integer
    integration-testing
    intellij-idea
    interface
    interface-builder
    internationalization
    internet-explorer
    internet-explorer-11
    internet-explorer-8
    interop
    io
    ionic-framework
    ionic2
    ionic3
    ionic4
    ios
    ios-simulator
    ios4
    ios5
    ios6
    ios7
    ios8
    ip
    ipad
    iphone
    ipython
    iteration
    iterator
    itext
    jackson
    jakarta-ee
    jakarta-mail
    jar
    jasmine
    jasper-reports
    java
    java-8
    java-me
    java-native-interface
    java-stream
    java.util.scanner
    javafx
    javafx-8
    javascript
    javascript-objects
    jax-rs
    jaxb
    jboss
    jdbc
    jekyll
    jenkins
    jenkins-pipeline
    jenkins-plugins
    jersey
    jestjs
    jetty
    jframe
    jinja2
    jira
    jmeter
    jms
    join
    joomla
    jpa
    jpanel
    jq
    jqgrid
    jquery
    jquery-animate
    jquery-mobile
    jquery-plugins
    jquery-selectors
    jquery-ui
    jquery-validate
    jsf
    jsf-2
    json
    json.net
    jsoup
    jsp
    jstl
    jsx
    jtable
    julia
    junit
    jupyter
    jupyter-notebook
    jvm
    jwt
    karma-jasmine
    kendo-grid
    kendo-ui
    keras
    kernel
    key
    keyboard
    keyboard-shortcuts
    keycloak
    kibana
    kivy
    knockout.js
    kotlin
    kubernetes
    label
    lambda
    language-agnostic
    language-lawyer
    laravel
    laravel-4
    laravel-5
    laravel-5.2
    laravel-8
    latex
    layout
    lazy-loading
    ldap
    leaflet
    left-join
    less
    libgdx
    liferay
    line
    linear-regression
    linked-list
    linker
    linq
    linq-to-entities
    linq-to-sql
    linux
    linux-kernel
    lisp
    list
    list-comprehension
    listbox
    listener
    listview
    llvm
    load
    local-storage
    localhost
    localization
    location
    locking
    lodash
    log4j
    logging
    logic
    login
    logstash
    loops
    lstm
    lua
    lucene
    lxml
    machine-learning
    macos
    macros
    magento
    makefile
    malloc
    many-to-many
    map
    mapbox
    mapkit
    mapping
    mapreduce
    maps
    mariadb
    markdown
    match
    material-design
    material-ui
    math
    matlab
    matplotlib
    matrix
    maven
    maven-2
    maven-3
    max
    media-queries
    memcached
    memory
    memory-leaks
    memory-management
    menu
    mercurial
    merge
    metadata
    meteor
    methods
    mfc
    microservices
    microsoft-graph-api
    migration
    mingw
    mips
    mobile
    mocha.js
    mocking
    mockito
    mod-rewrite
    modal-dialog
    model
    model-view-controller
    module
    momentjs
    mongodb
    mongodb-query
    mongoose
    mono
    moq
    mouseevent
    mpi
    mqtt
    ms-access
    ms-access-2010
    ms-office
    ms-word
    msbuild
    mule
    multidimensional-array
    multiple-columns
    multiprocessing
    multithreading
    mvvm
    mysql
    mysql-workbench
    mysqli
    namespaces
    nativescript
    navbar
    navigation
    navigation-drawer
    neo4j
    nested
    nestjs
    netbeans
    network-programming
    networking
    networkx
    neural-network
    next.js
    nginx
    nhibernate
    nlp
    nltk
    node-modules
    node.js
    nodes
    nosql
    notepad++
    notifications
    npm
    nsarray
    nsmutablearray
    nsstring
    nuget
    null
    nullpointerexception
    numbers
    numpy
    nunit
    nuxt.js
    oauth
    oauth-2.0
    object
    objective-c
    observable
    ocaml
    ocr
    octave
    odata
    odbc
    odoo
    office365
    onclick
    oop
    opencart
    opencl
    opencv
    openerp
    opengl
    opengl-es
    openmp
    openshift
    openssl
    operating-system
    operator-overloading
    operators
    optimization
    oracle
    oracle-apex
    oracle-sqldeveloper
    oracle10g
    oracle11g
    orm
    osgi
    out-of-memory
    outlook
    output
    overflow
    overloading
    overriding
    package
    pagination
    pandas
    pandas-groupby
    parallel-processing
    parameter-passing
    parameters
    parse-platform
    parsing
    passport.js
    passwords
    path
    pattern-matching
    paypal
    pdf
    pdf-generation
    pdo
    performance
    perl
    permissions
    phantomjs
    php
    phpmailer
    phpmyadmin
    phpstorm
    phpunit
    pip
    pipe
    pivot
    pivot-table
    playframework
    playframework-2.0
    plot
    plotly
    plsql
    plugins
    png
    pointers
    polymer
    polymorphism
    popup
    port
    position
    posix
    post
    postgresql
    postman
    powerbi
    powerpoint
    powershell
    preg-match
    preg-replace
    prepared-statement
    prestashop
    primefaces
    printf
    printing
    process
    processing
    profiling
    progress-bar
    prolog
    promise
    properties
    protocol-buffers
    protocols
    prototype
    protractor
    proxy
    pthreads
    pug
    puppeteer
    push
    push-notification
    pycharm
    pygame
    pyinstaller
    pymongo
    pyqt
    pyqt4
    pyqt5
    pyspark
    pytest
    python
    python-2.7
    python-3.6
    python-3.x
    python-asyncio
    python-imaging-library
    python-import
    python-requests
    pytorch
    qml
    qt
    qt4
    qt5
    query-optimization
    queue
    r
    r-markdown
    rabbitmq
    racket
    radio-button
    random
    range
    raspberry-pi
    razor
    react-hooks
    react-native
    react-native-android
    react-navigation
    react-redux
    react-router
    react-router-dom
    reactive-programming
    reactjs
    realm
    recursion
    redirect
    redis
    redux
    refactoring
    reference
    reflection
    refresh
    regex
    registry
    regression
    relational-database
    relationship
    rendering
    replace
    report
    reporting-services
    repository
    request
    requirejs
    resize
    resources
    response
    responsive-design
    rest
    retrofit
    retrofit2
    robotframework
    rotation
    rounding
    routes
    routing
    row
    rsa
    rspec
    rss
    rstudio
    ruby
    ruby-on-rails
    ruby-on-rails-3
    ruby-on-rails-3.1
    ruby-on-rails-3.2
    ruby-on-rails-4
    ruby-on-rails-5
    rubygems
    runtime
    runtime-error
    rust
    rx-java
    rxjs
    safari
    sails.js
    salesforce
    sapui5
    sas
    sass
    save
    sbt
    scala
    scanf
    scheduled-tasks
    schema
    scheme
    scikit-learn
    scipy
    scope
    scrapy
    scripting
    scroll
    scrollbar
    scrollview
    sdk
    seaborn
    search
    security
    sed
    segmentation-fault
    segue
    selenium
    selenium-chromedriver
    selenium-webdriver
    seo
    sequelize.js
    sequence
    serial-port
    serialization
    server
    service
    servicestack
    servlets
    session
    set
    settings
    sh
    shader
    shared-libraries
    sharedpreferences
    sharepoint
    sharepoint-2010
    shell
    shiny
    shopify
    signal-processing
    signalr
    signals
    silverlight
    silverlight-4.0
    sinatra
    single-page-application
    single-sign-on
    singleton
    sitecore
    size
    slice
    slider
    sms
    smtp
    snowflake-cloud-data-platform
    soap
    socket.io
    sockets
    solr
    sonarqube
    sorting
    spark-streaming
    sparql
    speech-recognition
    spinner
    split
    spring
    spring-batch
    spring-boot
    spring-data
    spring-data-jpa
    spring-integration
    spring-mvc
    spring-security
    sprite-kit
    sql
    sql-order-by
    sql-server
    sql-server-2005
    sql-server-2008
    sql-server-2008-r2
    sql-server-2012
    sql-update
    sqlalchemy
    sqlite
    ssas
    ssh
    ssis
    ssl
    ssl-certificate
    ssms
    ssrs-2008
    stack
    state
    static
    statistics
    stl
    storage
    stored-procedures
    storyboard
    stream
    streaming
    string
    stripe-payments
    struct
    structure
    struts2
    styles
    subdomain
    sublimetext3
    submit
    subprocess
    subquery
    subset
    substring
    sum
    svg
    svn
    swagger
    swift
    swift2
    swift3
    swift4
    swiftui
    swing
    switch-statement
    swt
    symfony
    synchronization
    syntax
    syntax-error
    tableau-api
    tableview
    tabs
    tags
    task
    task-parallel-library
    tcl
    tcp
    tdd
    teamcity
    telerik
    templates
    tensorflow
    tensorflow2.0
    teradata
    terminal
    terraform
    testing
    testng
    text
    text-files
    textarea
    textbox
    textures
    textview
    tfs
    themes
    this
    thread-safety
    three.js
    thymeleaf
    tidyverse
    time
    time-complexity
    time-series
    timeout
    timer
    timestamp
    timezone
    tinymce
    titanium
    tkinter
    toggle
    token
    tomcat
    tomcat7
    tooltip
    touch
    transactions
    transform
    tree
    treeview
    triggers
    try-catch
    tsql
    tuples
    twig
    twilio
    twitter
    twitter-bootstrap
    twitter-bootstrap-3
    type-conversion
    typeerror
    types
    typescript
    typo3
    ubuntu
    udp
    uibutton
    uicollectionview
    uiimage
    uiimageview
    uikit
    uilabel
    uinavigationbar
    uinavigationcontroller
    uiscrollview
    uitabbarcontroller
    uitableview
    uitextfield
    uitextview
    uiview
    uiviewcontroller
    uiwebview
    uml
    undefined
    underscore.js
    unicode
    union
    unique
    unit-testing
    unity3d
    unix
    upload
    uri
    url
    url-rewriting
    usb
    user-controls
    user-input
    user-interface
    utf-8
    uwp
    vaadin
    vagrant
    validation
    variables
    vb.net
    vb6
    vba
    vbscript
    vector
    vectorization
    verilog
    version
    version-control
    vhdl
    video
    video-streaming
    view
    vim
    virtual-machine
    virtualbox
    virtualenv
    visual-c++
    visual-studio
    visual-studio-2008
    visual-studio-2010
    visual-studio-2012
    visual-studio-2013
    visual-studio-2015
    visual-studio-2017
    visual-studio-2019
    visual-studio-code
    vsto
    vue-component
    vue-router
    vue.js
    vuejs2
    vuetify.js
    vuex
    wamp
    warnings
    wcf
    web
    web-applications
    web-config
    web-crawler
    web-scraping
    web-services
    webdriver
    webforms
    webgl
    webkit
    weblogic
    webpack
    webrtc
    webserver
    websocket
    websphere
    webstorm
    webview
    while-loop
    widget
    width
    wifi
    wildfly
    win-universal-app
    winapi
    window
    windows
    windows-10
    windows-7
    windows-8
    windows-installer
    windows-phone
    windows-phone-7
    windows-phone-8
    windows-phone-8.1
    windows-runtime
    windows-services
    windows-store-apps
    winforms
    wix
    woocommerce
    wordpress
    wordpress-theming
    workflow
    wpf
    wpf-controls
    wsdl
    wso2
    wxpython
    x86
    x86-64
    xamarin
    xamarin.android
    xamarin.forms
    xamarin.ios
    xaml
    xampp
    xcode
    xcode4
    xcode6
    xhtml
    xml
    xml-parsing
    xmlhttprequest
    xmpp
    xna
    xpages
    xpath
    xquery
    xsd
    xslt
    xslt-1.0
    yaml
    yii
    yii2
    youtube
    youtube-api
    zend-framework
    zend-framework2
    zip
    zooming
    zsh
    zurb-foundation
  ].freeze
end
